environment:
  env_name: Hockey-v0
  n_envs: 32
  seed: 42
  reward_multiplier: 10
  additional_rewards:
  - puck_proximity
  - offensive_pressure
rnd:
  enabled: false
  use_only_intrinsic: false
  intrinsic_reward_weight: 0.1
  non_episodic: true
  rnd_hidden_size: 128
model:
  name: ppo
  models_dir: ppo/models/
  noise: null
  hyperparameters:
    learning_rate: 0.00073
    n_steps: 512
    batch_size: 512
    n_epochs: 5
    gamma: 0.999
    gae_lambda: 0.95
    clip_range: 0.2
    clip_range_vf: null
    normalize_advantage: true
    use_sde: false
    sde_sample_freq: -1
    target_kl: null
    vf_coef: 0.6482388887006054
    ent_coef: 0.0009673352
    max_grad_norm: 0.6
    policy_kwargs:
      net_arch:
      - 256
      - 256
      ortho_init: true
      activation_fn: relu
training:
  total_timesteps: 40000000
  log_interval: 1
  model_path: models/ppo/ppo_pp+op
  save_model_every: 50000
logging:
  log_dir: ./logs/
  verbose: 0
  tensorboard: ./ppo/logs/temp/
