# ppo_config.yaml

environment:
  env_name: Hockey-v0
  n_envs: 1
  seed: 42
  reward_multiplier: 10
  additional_rewards: []

model:
  name: ppo  # Could be ppo, sac, etc.
  models_dir: ppo/models/
  hyperparameters:
    learning_rate: 0.0003
    n_steps: 256
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    vf_coef: 0.5
    ent_coef: 0.01
    max_grad_norm: 0.5

training:
  total_timesteps: 3000
  log_interval: 1
  model_path: ppo/models/ppo_test

logging:
  log_dir: ./logs/
  verbose: 1
  tensorboard: ./ppo/logs/
