environment:
  env_name: "Hockey-v0"
  n_envs: 1
  seed: 42
  reward_multiplier: 10
  additional_rewards: []

model:
  name: "td3"  # Could be "td3", "sac", etc.
  models_dir: "td3/models/"
  hyperparameters:
    learning_rate: 0.001  # learning rate for adam optimizer
    buffer_size: 1000000  # size of the replay buffer
    learning_starts: 10000  # how many steps of the model to collect transitions for before learning starts
    batch_size: 100  # Minibatch size for each gradient update
    tau: 0.005  # the soft update coefficient ("Polyak update", between 0 and 1)
    gamma: 0.99  # the discount factor
    train_freq: 1  # Update the model every `train_freq` steps
    gradient_steps: 1  # How many gradient steps to do after each rollout (see `train_freq`)
    policy_delay: 2  # Policy and target networks will only be updated once every `policy_delay` steps
    target_policy_noise: 0.2  # Standard deviation of Gaussian noise added to target policy (smoothing noise)
    target_noise_clip: 0.5  # Limit for absolute value of target policy smoothing noise
    # action_noise:
    #   type: "normal"  # Standard exploration noise
    #   mean: 0.0
    #   std: 0.1

training:
  total_timesteps: 500000
  log_interval: 1
  save_model_every: 10000
  model_path: "td3/models/td3_hockey"

logging:
  log_dir: "./logs/"
  verbose: 1
  tensorboard: "./logs/tensorboard/"